# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.
[[main]]
  name = "Home"
  url = "/"
  weight = 10

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "About"
  pageRef = "about"
  url = "/about"
  weight = 30

[[main]]
  name = "Resume"
  pageRef = "resume"
  url = "/resume"
  weight = 40

[[main]]
  name = "Links"
  pageRef = "links"
  url = "/links"
  weight = 50


[[main]]
  identifier = "rss"
  pre = "rss-solid"
  url = "/index.xml"
  weight = 60

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10
# 
# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
