# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Sajay Prakash 
description:      'My personal site'
baseurl:          'https://sajayprakash.com'
url:              ''             

author:
  name:           'Sajay Prakash'

paginate:         5

version:          2.1.0

plugins:
  - jekyll-gist
  - jekyll-paginate

github:
  repo: https://github.com/sajayprakash/
